// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/ActionMenuView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type ActionMenuView struct {
	View
}

func NewActionMenuView(id string) interface{} {
	obj := ActionMenuView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["ActionMenuView"] = NewActionMenuView
}

func (obj ActionMenuView) DismissPopupMenus() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"dismissPopupMenus",
	)
}

func (obj ActionMenuView) GetPopupTheme() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"getPopupTheme",
	)
}

func (obj ActionMenuView) HideOverflowMenu() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"hideOverflowMenu",
	)
}

func (obj ActionMenuView) IsOverflowMenuShowing() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"isOverflowMenuShowing",
	)
}

func (obj ActionMenuView) OnDetachedFromWindow() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"onDetachedFromWindow",
	)
}

func (obj ActionMenuView) SetPopupTheme(resId_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"setPopupTheme",
		resId_,
	)
}

func (obj ActionMenuView) ShowOverflowMenu() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"ActionMenuView",
		"showOverflowMenu",
	)
}

