// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/AdapterView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type AdapterView struct {
	View
}

func NewAdapterView(id string) interface{} {
	obj := AdapterView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["AdapterView"] = NewAdapterView
}

func (obj AdapterView) GetCount() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"getCount",
	)
}

func (obj AdapterView) GetFirstVisiblePosition() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"getFirstVisiblePosition",
	)
}

func (obj AdapterView) GetLastVisiblePosition() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"getLastVisiblePosition",
	)
}

func (obj AdapterView) GetSelectedItemPosition() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"getSelectedItemPosition",
	)
}

func (obj AdapterView) RemoveAllViews() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"removeAllViews",
	)
}

func (obj AdapterView) RemoveViewAt(index_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"removeViewAt",
		index_,
	)
}

func (obj AdapterView) SetFocusable(focusable_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"setFocusable",
		focusable_,
	)
}

func (obj AdapterView) SetFocusableInTouchMode(focusable_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AdapterView",
		"setFocusableInTouchMode",
		focusable_,
	)
}

