// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/AutoCompleteTextView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type AutoCompleteTextView struct {
	View
}

func NewAutoCompleteTextView(id string) interface{} {
	obj := AutoCompleteTextView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["AutoCompleteTextView"] = NewAutoCompleteTextView
}

func (obj AutoCompleteTextView) ClearListSelection() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"clearListSelection",
	)
}

func (obj AutoCompleteTextView) DismissDropDown() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"dismissDropDown",
	)
}

func (obj AutoCompleteTextView) EnoughToFilter() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"enoughToFilter",
	)
}

func (obj AutoCompleteTextView) GetCompletionHint() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getCompletionHint",
	)
}

func (obj AutoCompleteTextView) GetDropDownAnchor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getDropDownAnchor",
	)
}

func (obj AutoCompleteTextView) GetDropDownHeight() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getDropDownHeight",
	)
}

func (obj AutoCompleteTextView) GetDropDownHorizontalOffset() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getDropDownHorizontalOffset",
	)
}

func (obj AutoCompleteTextView) GetDropDownVerticalOffset() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getDropDownVerticalOffset",
	)
}

func (obj AutoCompleteTextView) GetDropDownWidth() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getDropDownWidth",
	)
}

func (obj AutoCompleteTextView) GetListSelection() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getListSelection",
	)
}

func (obj AutoCompleteTextView) GetThreshold() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"getThreshold",
	)
}

func (obj AutoCompleteTextView) IsPerformingCompletion() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"isPerformingCompletion",
	)
}

func (obj AutoCompleteTextView) IsPopupShowing() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"isPopupShowing",
	)
}

func (obj AutoCompleteTextView) OnFilterComplete(count_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"onFilterComplete",
		count_,
	)
}

func (obj AutoCompleteTextView) OnWindowFocusChanged(hasWindowFocus_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"onWindowFocusChanged",
		hasWindowFocus_,
	)
}

func (obj AutoCompleteTextView) PerformCompletion() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"performCompletion",
	)
}

func (obj AutoCompleteTextView) PerformValidation() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"performValidation",
	)
}

func (obj AutoCompleteTextView) SetCompletionHint(hint_ string) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setCompletionHint",
		hint_,
	)
}

func (obj AutoCompleteTextView) SetDropDownAnchor(id_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownAnchor",
		id_,
	)
}

func (obj AutoCompleteTextView) SetDropDownBackgroundResource(id_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownBackgroundResource",
		id_,
	)
}

func (obj AutoCompleteTextView) SetDropDownHeight(height_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownHeight",
		height_,
	)
}

func (obj AutoCompleteTextView) SetDropDownHorizontalOffset(offset_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownHorizontalOffset",
		offset_,
	)
}

func (obj AutoCompleteTextView) SetDropDownVerticalOffset(offset_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownVerticalOffset",
		offset_,
	)
}

func (obj AutoCompleteTextView) SetDropDownWidth(width_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setDropDownWidth",
		width_,
	)
}

func (obj AutoCompleteTextView) SetListSelection(position_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setListSelection",
		position_,
	)
}

func (obj AutoCompleteTextView) SetText(text_ string, filter_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setText",
		text_, filter_,
	)
}

func (obj AutoCompleteTextView) SetThreshold(threshold_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"setThreshold",
		threshold_,
	)
}

func (obj AutoCompleteTextView) ShowDropDown() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"AutoCompleteTextView",
		"showDropDown",
	)
}

