// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/AutoCompleteTextView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type AutoCompleteTextView struct {
	View
}

func NewAutoCompleteTextView(id string) interface{} {
	obj := AutoCompleteTextView{NewView(id).(View)}

	return obj
}

func (obj AutoCompleteTextView) GetClassName() string {
	return "android.widget.AutoCompleteTextView"
}

func init() {
	android.ViewTypeConstructors["android.widget.AutoCompleteTextView"] = NewAutoCompleteTextView
}

func (obj AutoCompleteTextView) ClearListSelection() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"clearListSelection",
	)
}

func (obj AutoCompleteTextView) DismissDropDown() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"dismissDropDown",
	)
}

func (obj AutoCompleteTextView) EnoughToFilter() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"enoughToFilter",
	)
}

func (obj AutoCompleteTextView) GetCompletionHint() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getCompletionHint",
	)
}

func (obj AutoCompleteTextView) GetDropDownAnchor() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getDropDownAnchor",
	)
}

func (obj AutoCompleteTextView) GetDropDownHeight() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getDropDownHeight",
	)
}

func (obj AutoCompleteTextView) GetDropDownHorizontalOffset() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getDropDownHorizontalOffset",
	)
}

func (obj AutoCompleteTextView) GetDropDownVerticalOffset() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getDropDownVerticalOffset",
	)
}

func (obj AutoCompleteTextView) GetDropDownWidth() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getDropDownWidth",
	)
}

func (obj AutoCompleteTextView) GetListSelection() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getListSelection",
	)
}

func (obj AutoCompleteTextView) GetThreshold() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"getThreshold",
	)
}

func (obj AutoCompleteTextView) IsPerformingCompletion() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"isPerformingCompletion",
	)
}

func (obj AutoCompleteTextView) IsPopupShowing() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"isPopupShowing",
	)
}

func (obj AutoCompleteTextView) OnFilterComplete(count_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"onFilterComplete",
		count_,
	)
}

func (obj AutoCompleteTextView) OnWindowFocusChanged(hasWindowFocus_ bool) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"onWindowFocusChanged",
		hasWindowFocus_,
	)
}

func (obj AutoCompleteTextView) PerformCompletion() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"performCompletion",
	)
}

func (obj AutoCompleteTextView) PerformValidation() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"performValidation",
	)
}

func (obj AutoCompleteTextView) SetCompletionHint(hint_ string) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setCompletionHint",
		hint_,
	)
}

func (obj AutoCompleteTextView) SetDropDownAnchor(id_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownAnchor",
		id_,
	)
}

func (obj AutoCompleteTextView) SetDropDownBackgroundResource(id_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownBackgroundResource",
		id_,
	)
}

func (obj AutoCompleteTextView) SetDropDownHeight(height_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownHeight",
		height_,
	)
}

func (obj AutoCompleteTextView) SetDropDownHorizontalOffset(offset_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownHorizontalOffset",
		offset_,
	)
}

func (obj AutoCompleteTextView) SetDropDownVerticalOffset(offset_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownVerticalOffset",
		offset_,
	)
}

func (obj AutoCompleteTextView) SetDropDownWidth(width_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setDropDownWidth",
		width_,
	)
}

func (obj AutoCompleteTextView) SetListSelection(position_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setListSelection",
		position_,
	)
}

func (obj AutoCompleteTextView) SetText(text_ string, filter_ bool) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setText",
		text_, filter_,
	)
}

func (obj AutoCompleteTextView) SetThreshold(threshold_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"setThreshold",
		threshold_,
	)
}

func (obj AutoCompleteTextView) ShowDropDown() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.AutoCompleteTextView",
		"showDropDown",
	)
}

