// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/CalendarView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type CalendarView struct {
	View
}

func NewCalendarView(id string) interface{} {
	obj := CalendarView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["CalendarView"] = NewCalendarView
}

func (obj CalendarView) GetDateTextAppearance() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getDateTextAppearance",
	)
}

func (obj CalendarView) GetFirstDayOfWeek() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getFirstDayOfWeek",
	)
}

func (obj CalendarView) GetFocusedMonthDateColor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getFocusedMonthDateColor",
	)
}

func (obj CalendarView) GetSelectedWeekBackgroundColor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getSelectedWeekBackgroundColor",
	)
}

func (obj CalendarView) GetShowWeekNumber() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getShowWeekNumber",
	)
}

func (obj CalendarView) GetShownWeekCount() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getShownWeekCount",
	)
}

func (obj CalendarView) GetUnfocusedMonthDateColor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getUnfocusedMonthDateColor",
	)
}

func (obj CalendarView) GetWeekDayTextAppearance() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getWeekDayTextAppearance",
	)
}

func (obj CalendarView) GetWeekNumberColor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getWeekNumberColor",
	)
}

func (obj CalendarView) GetWeekSeparatorLineColor() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"getWeekSeparatorLineColor",
	)
}

func (obj CalendarView) IsEnabled() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"isEnabled",
	)
}

func (obj CalendarView) SetDateTextAppearance(resourceId_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setDateTextAppearance",
		resourceId_,
	)
}

func (obj CalendarView) SetEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setEnabled",
		enabled_,
	)
}

func (obj CalendarView) SetFirstDayOfWeek(firstDayOfWeek_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setFirstDayOfWeek",
		firstDayOfWeek_,
	)
}

func (obj CalendarView) SetFocusedMonthDateColor(color_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setFocusedMonthDateColor",
		color_,
	)
}

func (obj CalendarView) SetSelectedDateVerticalBar(resourceId_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setSelectedDateVerticalBar",
		resourceId_,
	)
}

func (obj CalendarView) SetSelectedWeekBackgroundColor(color_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setSelectedWeekBackgroundColor",
		color_,
	)
}

func (obj CalendarView) SetShowWeekNumber(showWeekNumber_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setShowWeekNumber",
		showWeekNumber_,
	)
}

func (obj CalendarView) SetShownWeekCount(count_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setShownWeekCount",
		count_,
	)
}

func (obj CalendarView) SetUnfocusedMonthDateColor(color_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setUnfocusedMonthDateColor",
		color_,
	)
}

func (obj CalendarView) SetWeekDayTextAppearance(resourceId_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setWeekDayTextAppearance",
		resourceId_,
	)
}

func (obj CalendarView) SetWeekNumberColor(color_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setWeekNumberColor",
		color_,
	)
}

func (obj CalendarView) SetWeekSeparatorLineColor(color_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"CalendarView",
		"setWeekSeparatorLineColor",
		color_,
	)
}

