// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/EditText.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type EditText struct {
	TextView
}

func NewEditText(id string) interface{} {
	obj := EditText{NewTextView(id).(TextView)}

	return obj
}

func (obj EditText) GetClassName() string {
	return "android.widget.EditText"
}

func init() {
	android.ViewTypeConstructors["android.widget.EditText"] = NewEditText
}

func (obj EditText) ExtendSelection(index_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.EditText",
		"extendSelection",
		index_,
	))
}

func (obj EditText) SelectAll() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.EditText",
		"selectAll",
	))
}

func (obj EditText) SetSelection(index_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.EditText",
		"setSelection",
		index_,
	))
}

func (obj EditText) SetSelection2ii(start_ int, stop_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.EditText",
		"setSelection",
		start_, stop_,
	))
}

