// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/HorizontalScrollView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type HorizontalScrollView struct {
	View
}

func NewHorizontalScrollView(id string) interface{} {
	obj := HorizontalScrollView{NewView(id).(View)}

	return obj
}

func (obj HorizontalScrollView) GetClassName() string {
	return "android.widget.HorizontalScrollView"
}

func init() {
	android.ViewTypeConstructors["android.widget.HorizontalScrollView"] = NewHorizontalScrollView
}

func (obj HorizontalScrollView) ArrowScroll(direction_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"arrowScroll",
		direction_,
	)
}

func (obj HorizontalScrollView) ComputeScroll() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"computeScroll",
	)
}

func (obj HorizontalScrollView) Fling(velocityX_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"fling",
		velocityX_,
	)
}

func (obj HorizontalScrollView) FullScroll(direction_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"fullScroll",
		direction_,
	)
}

func (obj HorizontalScrollView) GetMaxScrollAmount() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"getMaxScrollAmount",
	)
}

func (obj HorizontalScrollView) IsFillViewport() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"isFillViewport",
	)
}

func (obj HorizontalScrollView) IsSmoothScrollingEnabled() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"isSmoothScrollingEnabled",
	)
}

func (obj HorizontalScrollView) PageScroll(direction_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"pageScroll",
		direction_,
	)
}

func (obj HorizontalScrollView) RequestDisallowInterceptTouchEvent(disallowIntercept_ bool) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"requestDisallowInterceptTouchEvent",
		disallowIntercept_,
	)
}

func (obj HorizontalScrollView) RequestLayout() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"requestLayout",
	)
}

func (obj HorizontalScrollView) ScrollTo(x_ int, y_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"scrollTo",
		x_, y_,
	)
}

func (obj HorizontalScrollView) SetFillViewport(fillViewport_ bool) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"setFillViewport",
		fillViewport_,
	)
}

func (obj HorizontalScrollView) SetOverScrollMode(mode_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"setOverScrollMode",
		mode_,
	)
}

func (obj HorizontalScrollView) SetSmoothScrollingEnabled(smoothScrollingEnabled_ bool) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"setSmoothScrollingEnabled",
		smoothScrollingEnabled_,
	)
}

func (obj HorizontalScrollView) ShouldDelayChildPressedState() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"shouldDelayChildPressedState",
	)
}

func (obj HorizontalScrollView) SmoothScrollBy(dx_ int, dy_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"smoothScrollBy",
		dx_, dy_,
	)
}

func (obj HorizontalScrollView) SmoothScrollTo(x_ int, y_ int) map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.HorizontalScrollView",
		"smoothScrollTo",
		x_, y_,
	)
}

