// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/ListView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type ListView struct {
	View
}

func NewListView(id string) interface{} {
	obj := ListView{NewView(id).(View)}

	return obj
}

func (obj ListView) GetClassName() string {
	return "android.widget.ListView"
}

func init() {
	android.ViewTypeConstructors["android.widget.ListView"] = NewListView
}

func (obj ListView) AreFooterDividersEnabled() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"areFooterDividersEnabled",
	))
}

func (obj ListView) AreHeaderDividersEnabled() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"areHeaderDividersEnabled",
	))
}

func (obj ListView) GetDividerHeight() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"getDividerHeight",
	))
}

func (obj ListView) GetFooterViewsCount() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"getFooterViewsCount",
	))
}

func (obj ListView) GetHeaderViewsCount() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"getHeaderViewsCount",
	))
}

func (obj ListView) GetItemsCanFocus() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"getItemsCanFocus",
	))
}

func (obj ListView) GetMaxScrollAmount() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"getMaxScrollAmount",
	))
}

func (obj ListView) IsOpaque() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"isOpaque",
	))
}

func (obj ListView) SetCacheColorHint(color_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setCacheColorHint",
		color_,
	))
}

func (obj ListView) SetDividerHeight(height_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setDividerHeight",
		height_,
	))
}

func (obj ListView) SetFooterDividersEnabled(footerDividersEnabled_ bool) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setFooterDividersEnabled",
		footerDividersEnabled_,
	))
}

func (obj ListView) SetHeaderDividersEnabled(headerDividersEnabled_ bool) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setHeaderDividersEnabled",
		headerDividersEnabled_,
	))
}

func (obj ListView) SetItemsCanFocus(itemsCanFocus_ bool) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setItemsCanFocus",
		itemsCanFocus_,
	))
}

func (obj ListView) SetSelection(position_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setSelection",
		position_,
	))
}

func (obj ListView) SetSelectionAfterHeaderView() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"setSelectionAfterHeaderView",
	))
}

func (obj ListView) SmoothScrollByOffset(offset_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"smoothScrollByOffset",
		offset_,
	))
}

func (obj ListView) SmoothScrollToPosition(position_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ListView",
		"smoothScrollToPosition",
		position_,
	))
}

