// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/ScrollView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type ScrollView struct {
	View
}

func NewScrollView(id string) interface{} {
	obj := ScrollView{NewView(id).(View)}

	return obj
}

func (obj ScrollView) GetClassName() string {
	return "android.widget.ScrollView"
}

func init() {
	android.ViewTypeConstructors["android.widget.ScrollView"] = NewScrollView
}

func (obj ScrollView) ArrowScroll(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"arrowScroll",
		direction_,
	)
}

func (obj ScrollView) ComputeScroll() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"computeScroll",
	)
}

func (obj ScrollView) Fling(velocityY_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"fling",
		velocityY_,
	)
}

func (obj ScrollView) FullScroll(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"fullScroll",
		direction_,
	)
}

func (obj ScrollView) GetMaxScrollAmount() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"getMaxScrollAmount",
	)
}

func (obj ScrollView) IsFillViewport() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"isFillViewport",
	)
}

func (obj ScrollView) IsSmoothScrollingEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"isSmoothScrollingEnabled",
	)
}

func (obj ScrollView) PageScroll(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"pageScroll",
		direction_,
	)
}

func (obj ScrollView) RequestDisallowInterceptTouchEvent(disallowIntercept_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"requestDisallowInterceptTouchEvent",
		disallowIntercept_,
	)
}

func (obj ScrollView) RequestLayout() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"requestLayout",
	)
}

func (obj ScrollView) ScrollTo(x_ int, y_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"scrollTo",
		x_, y_,
	)
}

func (obj ScrollView) SetFillViewport(fillViewport_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"setFillViewport",
		fillViewport_,
	)
}

func (obj ScrollView) SetOverScrollMode(mode_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"setOverScrollMode",
		mode_,
	)
}

func (obj ScrollView) SetSmoothScrollingEnabled(smoothScrollingEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"setSmoothScrollingEnabled",
		smoothScrollingEnabled_,
	)
}

func (obj ScrollView) ShouldDelayChildPressedState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"shouldDelayChildPressedState",
	)
}

func (obj ScrollView) SmoothScrollBy(dx_ int, dy_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"smoothScrollBy",
		dx_, dy_,
	)
}

func (obj ScrollView) SmoothScrollTo(x_ int, y_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.ScrollView",
		"smoothScrollTo",
		x_, y_,
	)
}

