// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/SearchView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type SearchView struct {
	View
}

func NewSearchView(id string) interface{} {
	obj := SearchView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["SearchView"] = NewSearchView
}

func (obj SearchView) GetImeOptions() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"getImeOptions",
	)
}

func (obj SearchView) GetInputType() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"getInputType",
	)
}

func (obj SearchView) GetMaxWidth() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"getMaxWidth",
	)
}

func (obj SearchView) GetQuery() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"getQuery",
	)
}

func (obj SearchView) GetQueryHint() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"getQueryHint",
	)
}

func (obj SearchView) IsIconfiedByDefault() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"isIconfiedByDefault",
	)
}

func (obj SearchView) IsIconified() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"isIconified",
	)
}

func (obj SearchView) IsQueryRefinementEnabled() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"isQueryRefinementEnabled",
	)
}

func (obj SearchView) IsSubmitButtonEnabled() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"isSubmitButtonEnabled",
	)
}

func (obj SearchView) OnActionViewCollapsed() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"onActionViewCollapsed",
	)
}

func (obj SearchView) OnActionViewExpanded() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"onActionViewExpanded",
	)
}

func (obj SearchView) OnWindowFocusChanged(hasWindowFocus_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"onWindowFocusChanged",
		hasWindowFocus_,
	)
}

func (obj SearchView) SetIconified(iconify_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setIconified",
		iconify_,
	)
}

func (obj SearchView) SetIconifiedByDefault(iconified_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setIconifiedByDefault",
		iconified_,
	)
}

func (obj SearchView) SetImeOptions(imeOptions_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setImeOptions",
		imeOptions_,
	)
}

func (obj SearchView) SetInputType(inputType_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setInputType",
		inputType_,
	)
}

func (obj SearchView) SetMaxWidth(maxpixels_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setMaxWidth",
		maxpixels_,
	)
}

func (obj SearchView) SetQuery(query_ string, submit_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setQuery",
		query_, submit_,
	)
}

func (obj SearchView) SetQueryHint(hint_ string) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setQueryHint",
		hint_,
	)
}

func (obj SearchView) SetQueryRefinementEnabled(enable_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setQueryRefinementEnabled",
		enable_,
	)
}

func (obj SearchView) SetSubmitButtonEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"SearchView",
		"setSubmitButtonEnabled",
		enabled_,
	)
}

