// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/StackView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type StackView struct {
	View
}

func NewStackView(id string) interface{} {
	obj := StackView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["StackView"] = NewStackView
}

func (obj StackView) Advance() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"StackView",
		"advance",
	)
}

func (obj StackView) ShowNext() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"StackView",
		"showNext",
	)
}

func (obj StackView) ShowPrevious() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"StackView",
		"showPrevious",
	)
}

