// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/TextView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type TextView struct {
	View
}

func NewTextView(id string) interface{} {
	obj := TextView{NewView(id).(View)}

	return obj
}

func (obj TextView) GetClassName() string {
	return "android.widget.TextView"
}

func init() {
	android.ViewTypeConstructors["android.widget.TextView"] = NewTextView
}

func (obj TextView) Append(text_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"append",
		text_,
	)
}

func (obj TextView) Append3sii(text_ string, start_ int, end_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"append",
		text_, start_, end_,
	)
}

func (obj TextView) BeginBatchEdit() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"beginBatchEdit",
	)
}

func (obj TextView) BringPointIntoView(offset_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"bringPointIntoView",
		offset_,
	)
}

func (obj TextView) CancelLongPress() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"cancelLongPress",
	)
}

func (obj TextView) ClearComposingText() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"clearComposingText",
	)
}

func (obj TextView) ComputeScroll() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"computeScroll",
	)
}

func (obj TextView) Debug(depth_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"debug",
		depth_,
	)
}

func (obj TextView) DidTouchFocusSelect() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"didTouchFocusSelect",
	)
}

func (obj TextView) EndBatchEdit() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"endBatchEdit",
	)
}

func (obj TextView) GetAutoLinkMask() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getAutoLinkMask",
	)
}

func (obj TextView) GetBaseline() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getBaseline",
	)
}

func (obj TextView) GetCompoundDrawablePadding() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundDrawablePadding",
	)
}

func (obj TextView) GetCompoundPaddingBottom() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingBottom",
	)
}

func (obj TextView) GetCompoundPaddingEnd() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingEnd",
	)
}

func (obj TextView) GetCompoundPaddingLeft() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingLeft",
	)
}

func (obj TextView) GetCompoundPaddingRight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingRight",
	)
}

func (obj TextView) GetCompoundPaddingStart() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingStart",
	)
}

func (obj TextView) GetCompoundPaddingTop() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCompoundPaddingTop",
	)
}

func (obj TextView) GetCurrentHintTextColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCurrentHintTextColor",
	)
}

func (obj TextView) GetCurrentTextColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getCurrentTextColor",
	)
}

func (obj TextView) GetError() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getError",
	)
}

func (obj TextView) GetExtendedPaddingBottom() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getExtendedPaddingBottom",
	)
}

func (obj TextView) GetExtendedPaddingTop() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getExtendedPaddingTop",
	)
}

func (obj TextView) GetFreezesText() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getFreezesText",
	)
}

func (obj TextView) GetGravity() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getGravity",
	)
}

func (obj TextView) GetHighlightColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getHighlightColor",
	)
}

func (obj TextView) GetHint() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getHint",
	)
}

func (obj TextView) GetImeActionId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getImeActionId",
	)
}

func (obj TextView) GetImeActionLabel() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getImeActionLabel",
	)
}

func (obj TextView) GetImeOptions() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getImeOptions",
	)
}

func (obj TextView) GetIncludeFontPadding() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getIncludeFontPadding",
	)
}

func (obj TextView) GetInputType() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getInputType",
	)
}

func (obj TextView) GetLineCount() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getLineCount",
	)
}

func (obj TextView) GetLineHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getLineHeight",
	)
}

func (obj TextView) GetLineSpacingExtra() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getLineSpacingExtra",
	)
}

func (obj TextView) GetLineSpacingMultiplier() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getLineSpacingMultiplier",
	)
}

func (obj TextView) GetLinksClickable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getLinksClickable",
	)
}

func (obj TextView) GetMarqueeRepeatLimit() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMarqueeRepeatLimit",
	)
}

func (obj TextView) GetMaxEms() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMaxEms",
	)
}

func (obj TextView) GetMaxHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMaxHeight",
	)
}

func (obj TextView) GetMaxLines() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMaxLines",
	)
}

func (obj TextView) GetMaxWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMaxWidth",
	)
}

func (obj TextView) GetMinEms() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMinEms",
	)
}

func (obj TextView) GetMinHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMinHeight",
	)
}

func (obj TextView) GetMinLines() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMinLines",
	)
}

func (obj TextView) GetMinWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getMinWidth",
	)
}

func (obj TextView) GetOffsetForPosition(x_ float64, y_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getOffsetForPosition",
		android.Float(x_), android.Float(y_),
	)
}

func (obj TextView) GetPaintFlags() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getPaintFlags",
	)
}

func (obj TextView) GetPrivateImeOptions() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getPrivateImeOptions",
	)
}

func (obj TextView) GetSelectionEnd() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getSelectionEnd",
	)
}

func (obj TextView) GetSelectionStart() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getSelectionStart",
	)
}

func (obj TextView) GetShadowColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getShadowColor",
	)
}

func (obj TextView) GetShadowDx() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getShadowDx",
	)
}

func (obj TextView) GetShadowDy() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getShadowDy",
	)
}

func (obj TextView) GetShadowRadius() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getShadowRadius",
	)
}

func (obj TextView) GetText() map[string]interface{} {
	return android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getText",
	)
}

func (obj TextView) GetTextScaleX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTextScaleX",
	)
}

func (obj TextView) GetTextSize() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTextSize",
	)
}

func (obj TextView) GetTotalPaddingBottom() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingBottom",
	)
}

func (obj TextView) GetTotalPaddingEnd() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingEnd",
	)
}

func (obj TextView) GetTotalPaddingLeft() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingLeft",
	)
}

func (obj TextView) GetTotalPaddingRight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingRight",
	)
}

func (obj TextView) GetTotalPaddingStart() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingStart",
	)
}

func (obj TextView) GetTotalPaddingTop() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"getTotalPaddingTop",
	)
}

func (obj TextView) HasOverlappingRendering() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"hasOverlappingRendering",
	)
}

func (obj TextView) HasSelection() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"hasSelection",
	)
}

func (obj TextView) IsCursorVisible() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"isCursorVisible",
	)
}

func (obj TextView) IsInputMethodTarget() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"isInputMethodTarget",
	)
}

func (obj TextView) IsSuggestionsEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"isSuggestionsEnabled",
	)
}

func (obj TextView) IsTextSelectable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"isTextSelectable",
	)
}

func (obj TextView) JumpDrawablesToCurrentState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"jumpDrawablesToCurrentState",
	)
}

func (obj TextView) Length() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"length",
	)
}

func (obj TextView) MoveCursorToVisibleOffset() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"moveCursorToVisibleOffset",
	)
}

func (obj TextView) OnBeginBatchEdit() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onBeginBatchEdit",
	)
}

func (obj TextView) OnCheckIsTextEditor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onCheckIsTextEditor",
	)
}

func (obj TextView) OnEditorAction(actionCode_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onEditorAction",
		actionCode_,
	)
}

func (obj TextView) OnEndBatchEdit() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onEndBatchEdit",
	)
}

func (obj TextView) OnFinishTemporaryDetach() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onFinishTemporaryDetach",
	)
}

func (obj TextView) OnPreDraw() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onPreDraw",
	)
}

func (obj TextView) OnRtlPropertiesChanged(layoutDirection_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onRtlPropertiesChanged",
		layoutDirection_,
	)
}

func (obj TextView) OnScreenStateChanged(screenState_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onScreenStateChanged",
		screenState_,
	)
}

func (obj TextView) OnStartTemporaryDetach() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onStartTemporaryDetach",
	)
}

func (obj TextView) OnTextContextMenuItem(id_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onTextContextMenuItem",
		id_,
	)
}

func (obj TextView) OnWindowFocusChanged(hasWindowFocus_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"onWindowFocusChanged",
		hasWindowFocus_,
	)
}

func (obj TextView) PerformLongClick() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"performLongClick",
	)
}

func (obj TextView) SendAccessibilityEvent(eventType_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"sendAccessibilityEvent",
		eventType_,
	)
}

func (obj TextView) SetAllCaps(allCaps_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setAllCaps",
		allCaps_,
	)
}

func (obj TextView) SetAutoLinkMask(mask_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setAutoLinkMask",
		mask_,
	)
}

func (obj TextView) SetCompoundDrawablePadding(pad_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setCompoundDrawablePadding",
		pad_,
	)
}

func (obj TextView) SetCompoundDrawablesRelativeWithIntrinsicBounds(start_ int, top_ int, end_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setCompoundDrawablesRelativeWithIntrinsicBounds",
		start_, top_, end_, bottom_,
	)
}

func (obj TextView) SetCompoundDrawablesWithIntrinsicBounds(left_ int, top_ int, right_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setCompoundDrawablesWithIntrinsicBounds",
		left_, top_, right_, bottom_,
	)
}

func (obj TextView) SetCursorVisible(visible_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setCursorVisible",
		visible_,
	)
}

func (obj TextView) SetEms(ems_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setEms",
		ems_,
	)
}

func (obj TextView) SetEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setEnabled",
		enabled_,
	)
}

func (obj TextView) SetError(error_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setError",
		error_,
	)
}

func (obj TextView) SetFilters() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setFilters",
	)
}

func (obj TextView) SetFreezesText(freezesText_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setFreezesText",
		freezesText_,
	)
}

func (obj TextView) SetGravity(gravity_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setGravity",
		gravity_,
	)
}

func (obj TextView) SetHeight(pixels_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHeight",
		pixels_,
	)
}

func (obj TextView) SetHighlightColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHighlightColor",
		color_,
	)
}

func (obj TextView) SetHint(hint_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHint",
		hint_,
	)
}

func (obj TextView) SetHint1i(resid_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHint",
		resid_,
	)
}

func (obj TextView) SetHintTextColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHintTextColor",
		color_,
	)
}

func (obj TextView) SetHorizontallyScrolling(whether_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setHorizontallyScrolling",
		whether_,
	)
}

func (obj TextView) SetImeActionLabel(label_ string, actionId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setImeActionLabel",
		label_, actionId_,
	)
}

func (obj TextView) SetImeOptions(imeOptions_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setImeOptions",
		imeOptions_,
	)
}

func (obj TextView) SetIncludeFontPadding(includepad_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setIncludeFontPadding",
		includepad_,
	)
}

func (obj TextView) SetInputExtras(xmlResId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setInputExtras",
		xmlResId_,
	)
}

func (obj TextView) SetInputType(type_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setInputType",
		type_,
	)
}

func (obj TextView) SetLineSpacing(add_ float64, mult_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setLineSpacing",
		android.Float(add_), android.Float(mult_),
	)
}

func (obj TextView) SetLines(lines_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setLines",
		lines_,
	)
}

func (obj TextView) SetLinkTextColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setLinkTextColor",
		color_,
	)
}

func (obj TextView) SetLinksClickable(whether_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setLinksClickable",
		whether_,
	)
}

func (obj TextView) SetMarqueeRepeatLimit(marqueeLimit_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMarqueeRepeatLimit",
		marqueeLimit_,
	)
}

func (obj TextView) SetMaxEms(maxems_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMaxEms",
		maxems_,
	)
}

func (obj TextView) SetMaxHeight(maxHeight_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMaxHeight",
		maxHeight_,
	)
}

func (obj TextView) SetMaxLines(maxlines_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMaxLines",
		maxlines_,
	)
}

func (obj TextView) SetMaxWidth(maxpixels_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMaxWidth",
		maxpixels_,
	)
}

func (obj TextView) SetMinEms(minems_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMinEms",
		minems_,
	)
}

func (obj TextView) SetMinHeight(minHeight_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMinHeight",
		minHeight_,
	)
}

func (obj TextView) SetMinLines(minlines_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMinLines",
		minlines_,
	)
}

func (obj TextView) SetMinWidth(minpixels_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setMinWidth",
		minpixels_,
	)
}

func (obj TextView) SetPadding(left_ int, top_ int, right_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setPadding",
		left_, top_, right_, bottom_,
	)
}

func (obj TextView) SetPaddingRelative(start_ int, top_ int, end_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setPaddingRelative",
		start_, top_, end_, bottom_,
	)
}

func (obj TextView) SetPaintFlags(flags_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setPaintFlags",
		flags_,
	)
}

func (obj TextView) SetPrivateImeOptions(type_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setPrivateImeOptions",
		type_,
	)
}

func (obj TextView) SetRawInputType(type_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setRawInputType",
		type_,
	)
}

func (obj TextView) SetSelectAllOnFocus(selectAllOnFocus_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setSelectAllOnFocus",
		selectAllOnFocus_,
	)
}

func (obj TextView) SetSelected(selected_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setSelected",
		selected_,
	)
}

func (obj TextView) SetShadowLayer(radius_ float64, dx_ float64, dy_ float64, color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setShadowLayer",
		android.Float(radius_), android.Float(dx_), android.Float(dy_), color_,
	)
}

func (obj TextView) SetSingleLine() {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setSingleLine",
	)
}

func (obj TextView) SetSingleLine1b(singleLine_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setSingleLine",
		singleLine_,
	)
}

func (obj TextView) SetText(resid_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setText",
		resid_,
	)
}

func (obj TextView) SetText2ii(start_ int, len_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setText",
		start_, len_,
	)
}

func (obj TextView) SetText1s(text_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setText",
		text_,
	)
}

func (obj TextView) SetTextColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextColor",
		color_,
	)
}

func (obj TextView) SetTextIsSelectable(selectable_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextIsSelectable",
		selectable_,
	)
}

func (obj TextView) SetTextKeepState(text_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextKeepState",
		text_,
	)
}

func (obj TextView) SetTextScaleX(size_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextScaleX",
		android.Float(size_),
	)
}

func (obj TextView) SetTextSize(size_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextSize",
		android.Float(size_),
	)
}

func (obj TextView) SetTextSize2if(unit_ int, size_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setTextSize",
		unit_, android.Float(size_),
	)
}

func (obj TextView) SetWidth(pixels_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.widget.TextView",
		"setWidth",
		pixels_,
	)
}
