// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/ToggleButton.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type ToggleButton struct {
	Button
}

func NewToggleButton(id string) interface{} {
	obj := ToggleButton{NewButton(id).(Button)}

	return obj
}

func (obj ToggleButton) GetClassName() string {
	return "android.widget.ToggleButton"
}

func init() {
	android.ViewTypeConstructors["android.widget.ToggleButton"] = NewToggleButton
}

func (obj ToggleButton) GetTextOff() (string, error) {
	return return_string(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ToggleButton",
		"getTextOff",
	))
}

func (obj ToggleButton) GetTextOn() (string, error) {
	return return_string(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ToggleButton",
		"getTextOn",
	))
}

func (obj ToggleButton) SetChecked(checked_ bool) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ToggleButton",
		"setChecked",
		checked_,
	))
}

func (obj ToggleButton) SetTextOff(textOff_ string) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ToggleButton",
		"setTextOff",
		textOff_,
	))
}

func (obj ToggleButton) SetTextOn(textOn_ string) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.ToggleButton",
		"setTextOn",
		textOn_,
	))
}

