// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/VideoView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type VideoView struct {
	View
}

func NewVideoView(id string) interface{} {
	obj := VideoView{NewView(id).(View)}

	return obj
}

func (obj VideoView) GetClassName() string {
	return "android.widget.VideoView"
}

func init() {
	android.ViewTypeConstructors["android.widget.VideoView"] = NewVideoView
}

func (obj VideoView) CanPause() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"canPause",
	))
}

func (obj VideoView) CanSeekBackward() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"canSeekBackward",
	))
}

func (obj VideoView) CanSeekForward() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"canSeekForward",
	))
}

func (obj VideoView) GetAudioSessionId() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"getAudioSessionId",
	))
}

func (obj VideoView) GetBufferPercentage() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"getBufferPercentage",
	))
}

func (obj VideoView) GetCurrentPosition() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"getCurrentPosition",
	))
}

func (obj VideoView) GetDuration() (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"getDuration",
	))
}

func (obj VideoView) IsPlaying() (bool, error) {
	return return_bool(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"isPlaying",
	))
}

func (obj VideoView) Pause() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"pause",
	))
}

func (obj VideoView) ResolveAdjustedSize(desiredSize_ int, measureSpec_ int) (int, error) {
	return return_int(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"resolveAdjustedSize",
		desiredSize_, measureSpec_,
	))
}

func (obj VideoView) Resume() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"resume",
	))
}

func (obj VideoView) SeekTo(msec_ int) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"seekTo",
		msec_,
	))
}

func (obj VideoView) SetVideoPath(path_ string) error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"setVideoPath",
		path_,
	))
}

func (obj VideoView) Start() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"start",
	))
}

func (obj VideoView) StopPlayback() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"stopPlayback",
	))
}

func (obj VideoView) Suspend() error {
	return return_error(android.CallViewMethod(
		obj.GetId(),
		"android.widget.VideoView",
		"suspend",
	))
}

