// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/widget/VideoView.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type VideoView struct {
	View
}

func NewVideoView(id string) interface{} {
	obj := VideoView{NewView(id).(View)}

	return obj
}


func init() {
	android.ViewTypeConstructors["VideoView"] = NewVideoView
}

func (obj VideoView) CanPause() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"canPause",
	)
}

func (obj VideoView) CanSeekBackward() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"canSeekBackward",
	)
}

func (obj VideoView) CanSeekForward() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"canSeekForward",
	)
}

func (obj VideoView) GetAudioSessionId() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"getAudioSessionId",
	)
}

func (obj VideoView) GetBufferPercentage() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"getBufferPercentage",
	)
}

func (obj VideoView) GetCurrentPosition() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"getCurrentPosition",
	)
}

func (obj VideoView) GetDuration() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"getDuration",
	)
}

func (obj VideoView) IsPlaying() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"isPlaying",
	)
}

func (obj VideoView) Pause() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"pause",
	)
}

func (obj VideoView) ResolveAdjustedSize(desiredSize_ int, measureSpec_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"resolveAdjustedSize",
		desiredSize_, measureSpec_,
	)
}

func (obj VideoView) Resume() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"resume",
	)
}

func (obj VideoView) SeekTo(msec_ int) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"seekTo",
		msec_,
	)
}

func (obj VideoView) SetVideoPath(path_ string) {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"setVideoPath",
		path_,
	)
}

func (obj VideoView) Start() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"start",
	)
}

func (obj VideoView) StopPlayback() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"stopPlayback",
	)
}

func (obj VideoView) Suspend() {
	android.CallViewMethod(
		obj.GetInternalId_(),
		"VideoView",
		"suspend",
	)
}

