// It is autogenerated bindings for Android sdk class.
//
// See documentation about methods on: https://developer.android.com//reference/android/view/View.html
package sdk

import "github.com/seletskiy/go-android-rpc/android"

type View struct {
	id string
}

func NewView(id string) interface{} {
	obj := View{}
	obj.id = id

	return obj
}

func (obj View) GetId() string  {
	return obj.id
}

func (obj View) GetClassName() string {
	return "android.view.View"
}

func init() {
	android.ViewTypeConstructors["android.view.View"] = NewView
}

func (obj View) AnnounceForAccessibility(text_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"announceForAccessibility",
		text_,
	)
}

func (obj View) BringToFront() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"bringToFront",
	)
}

func (obj View) BuildDrawingCache() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"buildDrawingCache",
	)
}

func (obj View) BuildDrawingCache1b(autoScale_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"buildDrawingCache",
		autoScale_,
	)
}

func (obj View) BuildLayer() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"buildLayer",
	)
}

func (obj View) CallOnClick() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"callOnClick",
	)
}

func (obj View) CanResolveLayoutDirection() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"canResolveLayoutDirection",
	)
}

func (obj View) CanResolveTextAlignment() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"canResolveTextAlignment",
	)
}

func (obj View) CanResolveTextDirection() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"canResolveTextDirection",
	)
}

func (obj View) CanScrollHorizontally(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"canScrollHorizontally",
		direction_,
	)
}

func (obj View) CanScrollVertically(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"canScrollVertically",
		direction_,
	)
}

func (obj View) CancelLongPress() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"cancelLongPress",
	)
}

func (obj View) CancelPendingInputEvents() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"cancelPendingInputEvents",
	)
}

func (obj View) ClearAnimation() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"clearAnimation",
	)
}

func (obj View) ClearFocus() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"clearFocus",
	)
}

func (obj View) ComputeScroll() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"computeScroll",
	)
}

func (obj View) DestroyDrawingCache() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"destroyDrawingCache",
	)
}

func (obj View) DispatchDisplayHint(hint_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"dispatchDisplayHint",
		hint_,
	)
}

func (obj View) DispatchSystemUiVisibilityChanged(visibility_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"dispatchSystemUiVisibilityChanged",
		visibility_,
	)
}

func (obj View) DispatchWindowFocusChanged(hasFocus_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"dispatchWindowFocusChanged",
		hasFocus_,
	)
}

func (obj View) DispatchWindowSystemUiVisiblityChanged(visible_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"dispatchWindowSystemUiVisiblityChanged",
		visible_,
	)
}

func (obj View) DispatchWindowVisibilityChanged(visibility_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"dispatchWindowVisibilityChanged",
		visibility_,
	)
}

func (obj View) ForceLayout() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"forceLayout",
	)
}

func (obj View) GetAccessibilityLiveRegion() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getAccessibilityLiveRegion",
	)
}

func (obj View) GetAlpha() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getAlpha",
	)
}

func (obj View) GetBaseline() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getBaseline",
	)
}

func (obj View) GetBottom() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getBottom",
	)
}

func (obj View) GetCameraDistance() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getCameraDistance",
	)
}

func (obj View) GetContentDescription() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getContentDescription",
	)
}

func (obj View) GetDrawingCacheBackgroundColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getDrawingCacheBackgroundColor",
	)
}

func (obj View) GetDrawingCacheQuality() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getDrawingCacheQuality",
	)
}

func (obj View) GetFilterTouchesWhenObscured() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getFilterTouchesWhenObscured",
	)
}

func (obj View) GetFitsSystemWindows() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getFitsSystemWindows",
	)
}

func (obj View) GetHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getHeight",
	)
}

func (obj View) GetHorizontalFadingEdgeLength() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getHorizontalFadingEdgeLength",
	)
}

func (obj View) GetImportantForAccessibility() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getImportantForAccessibility",
	)
}

func (obj View) GetKeepScreenOn() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getKeepScreenOn",
	)
}

func (obj View) GetLabelFor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLabelFor",
	)
}

func (obj View) GetLayerType() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLayerType",
	)
}

func (obj View) GetLayoutDirection() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLayoutDirection",
	)
}

func (obj View) GetLeft() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLeft",
	)
}

func (obj View) GetLocationInWindow() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLocationInWindow",
	)
}

func (obj View) GetLocationOnScreen() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getLocationOnScreen",
	)
}

func (obj View) GetMeasuredHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMeasuredHeight",
	)
}

func (obj View) GetMeasuredHeightAndState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMeasuredHeightAndState",
	)
}

func (obj View) GetMeasuredState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMeasuredState",
	)
}

func (obj View) GetMeasuredWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMeasuredWidth",
	)
}

func (obj View) GetMeasuredWidthAndState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMeasuredWidthAndState",
	)
}

func (obj View) GetMinimumHeight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMinimumHeight",
	)
}

func (obj View) GetMinimumWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getMinimumWidth",
	)
}

func (obj View) GetNextFocusDownId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getNextFocusDownId",
	)
}

func (obj View) GetNextFocusForwardId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getNextFocusForwardId",
	)
}

func (obj View) GetNextFocusLeftId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getNextFocusLeftId",
	)
}

func (obj View) GetNextFocusRightId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getNextFocusRightId",
	)
}

func (obj View) GetNextFocusUpId() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getNextFocusUpId",
	)
}

func (obj View) GetOverScrollMode() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getOverScrollMode",
	)
}

func (obj View) GetPaddingBottom() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingBottom",
	)
}

func (obj View) GetPaddingEnd() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingEnd",
	)
}

func (obj View) GetPaddingLeft() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingLeft",
	)
}

func (obj View) GetPaddingRight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingRight",
	)
}

func (obj View) GetPaddingStart() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingStart",
	)
}

func (obj View) GetPaddingTop() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPaddingTop",
	)
}

func (obj View) GetPivotX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPivotX",
	)
}

func (obj View) GetPivotY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getPivotY",
	)
}

func (obj View) GetRight() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getRight",
	)
}

func (obj View) GetRotation() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getRotation",
	)
}

func (obj View) GetRotationX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getRotationX",
	)
}

func (obj View) GetRotationY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getRotationY",
	)
}

func (obj View) GetScaleX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScaleX",
	)
}

func (obj View) GetScaleY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScaleY",
	)
}

func (obj View) GetScrollBarDefaultDelayBeforeFade() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollBarDefaultDelayBeforeFade",
	)
}

func (obj View) GetScrollBarFadeDuration() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollBarFadeDuration",
	)
}

func (obj View) GetScrollBarSize() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollBarSize",
	)
}

func (obj View) GetScrollBarStyle() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollBarStyle",
	)
}

func (obj View) GetScrollX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollX",
	)
}

func (obj View) GetScrollY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getScrollY",
	)
}

func (obj View) GetSolidColor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getSolidColor",
	)
}

func (obj View) GetSystemUiVisibility() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getSystemUiVisibility",
	)
}

func (obj View) GetTextAlignment() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getTextAlignment",
	)
}

func (obj View) GetTextDirection() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getTextDirection",
	)
}

func (obj View) GetTop() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getTop",
	)
}

func (obj View) GetTranslationX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getTranslationX",
	)
}

func (obj View) GetTranslationY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getTranslationY",
	)
}

func (obj View) GetVerticalFadingEdgeLength() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getVerticalFadingEdgeLength",
	)
}

func (obj View) GetVerticalScrollbarPosition() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getVerticalScrollbarPosition",
	)
}

func (obj View) GetVerticalScrollbarWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getVerticalScrollbarWidth",
	)
}

func (obj View) GetVisibility() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getVisibility",
	)
}

func (obj View) GetWidth() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getWidth",
	)
}

func (obj View) GetWindowSystemUiVisibility() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getWindowSystemUiVisibility",
	)
}

func (obj View) GetWindowVisibility() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getWindowVisibility",
	)
}

func (obj View) GetX() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getX",
	)
}

func (obj View) GetY() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"getY",
	)
}

func (obj View) HasFocus() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasFocus",
	)
}

func (obj View) HasFocusable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasFocusable",
	)
}

func (obj View) HasOnClickListeners() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasOnClickListeners",
	)
}

func (obj View) HasOverlappingRendering() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasOverlappingRendering",
	)
}

func (obj View) HasTransientState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasTransientState",
	)
}

func (obj View) HasWindowFocus() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"hasWindowFocus",
	)
}

func (obj View) Invalidate(l_ int, t_ int, r_ int, b_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"invalidate",
		l_, t_, r_, b_,
	)
}

func (obj View) Invalidate0() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"invalidate",
	)
}

func (obj View) IsActivated() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isActivated",
	)
}

func (obj View) IsAttachedToWindow() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isAttachedToWindow",
	)
}

func (obj View) IsClickable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isClickable",
	)
}

func (obj View) IsDirty() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isDirty",
	)
}

func (obj View) IsDrawingCacheEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isDrawingCacheEnabled",
	)
}

func (obj View) IsDuplicateParentStateEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isDuplicateParentStateEnabled",
	)
}

func (obj View) IsEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isEnabled",
	)
}

func (obj View) IsFocusable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isFocusable",
	)
}

func (obj View) IsFocusableInTouchMode() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isFocusableInTouchMode",
	)
}

func (obj View) IsFocused() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isFocused",
	)
}

func (obj View) IsHapticFeedbackEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isHapticFeedbackEnabled",
	)
}

func (obj View) IsHardwareAccelerated() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isHardwareAccelerated",
	)
}

func (obj View) IsHorizontalFadingEdgeEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isHorizontalFadingEdgeEnabled",
	)
}

func (obj View) IsHorizontalScrollBarEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isHorizontalScrollBarEnabled",
	)
}

func (obj View) IsHovered() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isHovered",
	)
}

func (obj View) IsInEditMode() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isInEditMode",
	)
}

func (obj View) IsInLayout() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isInLayout",
	)
}

func (obj View) IsInTouchMode() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isInTouchMode",
	)
}

func (obj View) IsLaidOut() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isLaidOut",
	)
}

func (obj View) IsLayoutDirectionResolved() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isLayoutDirectionResolved",
	)
}

func (obj View) IsLayoutRequested() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isLayoutRequested",
	)
}

func (obj View) IsLongClickable() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isLongClickable",
	)
}

func (obj View) IsOpaque() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isOpaque",
	)
}

func (obj View) IsPaddingRelative() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isPaddingRelative",
	)
}

func (obj View) IsPressed() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isPressed",
	)
}

func (obj View) IsSaveEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isSaveEnabled",
	)
}

func (obj View) IsSaveFromParentEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isSaveFromParentEnabled",
	)
}

func (obj View) IsScrollContainer() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isScrollContainer",
	)
}

func (obj View) IsScrollbarFadingEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isScrollbarFadingEnabled",
	)
}

func (obj View) IsSelected() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isSelected",
	)
}

func (obj View) IsShown() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isShown",
	)
}

func (obj View) IsSoundEffectsEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isSoundEffectsEnabled",
	)
}

func (obj View) IsTextAlignmentResolved() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isTextAlignmentResolved",
	)
}

func (obj View) IsTextDirectionResolved() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isTextDirectionResolved",
	)
}

func (obj View) IsVerticalFadingEdgeEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isVerticalFadingEdgeEnabled",
	)
}

func (obj View) IsVerticalScrollBarEnabled() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"isVerticalScrollBarEnabled",
	)
}

func (obj View) JumpDrawablesToCurrentState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"jumpDrawablesToCurrentState",
	)
}

func (obj View) Layout(l_ int, t_ int, r_ int, b_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"layout",
		l_, t_, r_, b_,
	)
}

func (obj View) Measure(widthMeasureSpec_ int, heightMeasureSpec_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"measure",
		widthMeasureSpec_, heightMeasureSpec_,
	)
}

func (obj View) OffsetLeftAndRight(offset_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"offsetLeftAndRight",
		offset_,
	)
}

func (obj View) OffsetTopAndBottom(offset_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"offsetTopAndBottom",
		offset_,
	)
}

func (obj View) OnCancelPendingInputEvents() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onCancelPendingInputEvents",
	)
}

func (obj View) OnCheckIsTextEditor() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onCheckIsTextEditor",
	)
}

func (obj View) OnFinishTemporaryDetach() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onFinishTemporaryDetach",
	)
}

func (obj View) OnHoverChanged(hovered_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onHoverChanged",
		hovered_,
	)
}

func (obj View) OnRtlPropertiesChanged(layoutDirection_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onRtlPropertiesChanged",
		layoutDirection_,
	)
}

func (obj View) OnScreenStateChanged(screenState_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onScreenStateChanged",
		screenState_,
	)
}

func (obj View) OnStartTemporaryDetach() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onStartTemporaryDetach",
	)
}

func (obj View) OnWindowFocusChanged(hasWindowFocus_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onWindowFocusChanged",
		hasWindowFocus_,
	)
}

func (obj View) OnWindowSystemUiVisibilityChanged(visible_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"onWindowSystemUiVisibilityChanged",
		visible_,
	)
}

func (obj View) PerformClick() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"performClick",
	)
}

func (obj View) PerformHapticFeedback(feedbackConstant_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"performHapticFeedback",
		feedbackConstant_,
	)
}

func (obj View) PerformHapticFeedback2ii(feedbackConstant_ int, flags_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"performHapticFeedback",
		feedbackConstant_, flags_,
	)
}

func (obj View) PerformLongClick() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"performLongClick",
	)
}

func (obj View) PlaySoundEffect(soundConstant_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"playSoundEffect",
		soundConstant_,
	)
}

func (obj View) PostInvalidate(left_ int, top_ int, right_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"postInvalidate",
		left_, top_, right_, bottom_,
	)
}

func (obj View) PostInvalidate0() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"postInvalidate",
	)
}

func (obj View) PostInvalidateOnAnimation(left_ int, top_ int, right_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"postInvalidateOnAnimation",
		left_, top_, right_, bottom_,
	)
}

func (obj View) PostInvalidateOnAnimation0() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"postInvalidateOnAnimation",
	)
}

func (obj View) RefreshDrawableState() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"refreshDrawableState",
	)
}

func (obj View) RequestFitSystemWindows() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"requestFitSystemWindows",
	)
}

func (obj View) RequestFocus(direction_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"requestFocus",
		direction_,
	)
}

func (obj View) RequestFocus0() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"requestFocus",
	)
}

func (obj View) RequestFocusFromTouch() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"requestFocusFromTouch",
	)
}

func (obj View) RequestLayout() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"requestLayout",
	)
}

func (obj View) ScrollBy(x_ int, y_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"scrollBy",
		x_, y_,
	)
}

func (obj View) ScrollTo(x_ int, y_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"scrollTo",
		x_, y_,
	)
}

func (obj View) SendAccessibilityEvent(eventType_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"sendAccessibilityEvent",
		eventType_,
	)
}

func (obj View) SetAccessibilityLiveRegion(mode_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setAccessibilityLiveRegion",
		mode_,
	)
}

func (obj View) SetActivated(activated_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setActivated",
		activated_,
	)
}

func (obj View) SetAlpha(alpha_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setAlpha",
		android.Float(alpha_),
	)
}

func (obj View) SetBackgroundColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setBackgroundColor",
		color_,
	)
}

func (obj View) SetBackgroundResource(resid_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setBackgroundResource",
		resid_,
	)
}

func (obj View) SetBottom(bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setBottom",
		bottom_,
	)
}

func (obj View) SetCameraDistance(distance_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setCameraDistance",
		android.Float(distance_),
	)
}

func (obj View) SetClickable(clickable_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setClickable",
		clickable_,
	)
}

func (obj View) SetContentDescription(contentDescription_ string) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setContentDescription",
		contentDescription_,
	)
}

func (obj View) SetDrawingCacheBackgroundColor(color_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setDrawingCacheBackgroundColor",
		color_,
	)
}

func (obj View) SetDrawingCacheEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setDrawingCacheEnabled",
		enabled_,
	)
}

func (obj View) SetDrawingCacheQuality(quality_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setDrawingCacheQuality",
		quality_,
	)
}

func (obj View) SetDuplicateParentStateEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setDuplicateParentStateEnabled",
		enabled_,
	)
}

func (obj View) SetEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setEnabled",
		enabled_,
	)
}

func (obj View) SetFadingEdgeLength(length_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setFadingEdgeLength",
		length_,
	)
}

func (obj View) SetFilterTouchesWhenObscured(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setFilterTouchesWhenObscured",
		enabled_,
	)
}

func (obj View) SetFitsSystemWindows(fitSystemWindows_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setFitsSystemWindows",
		fitSystemWindows_,
	)
}

func (obj View) SetFocusable(focusable_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setFocusable",
		focusable_,
	)
}

func (obj View) SetFocusableInTouchMode(focusableInTouchMode_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setFocusableInTouchMode",
		focusableInTouchMode_,
	)
}

func (obj View) SetHapticFeedbackEnabled(hapticFeedbackEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setHapticFeedbackEnabled",
		hapticFeedbackEnabled_,
	)
}

func (obj View) SetHasTransientState(hasTransientState_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setHasTransientState",
		hasTransientState_,
	)
}

func (obj View) SetHorizontalFadingEdgeEnabled(horizontalFadingEdgeEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setHorizontalFadingEdgeEnabled",
		horizontalFadingEdgeEnabled_,
	)
}

func (obj View) SetHorizontalScrollBarEnabled(horizontalScrollBarEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setHorizontalScrollBarEnabled",
		horizontalScrollBarEnabled_,
	)
}

func (obj View) SetHovered(hovered_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setHovered",
		hovered_,
	)
}

func (obj View) SetId(id_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setId",
		id_,
	)
}

func (obj View) SetImportantForAccessibility(mode_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setImportantForAccessibility",
		mode_,
	)
}

func (obj View) SetKeepScreenOn(keepScreenOn_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setKeepScreenOn",
		keepScreenOn_,
	)
}

func (obj View) SetLabelFor(id_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setLabelFor",
		id_,
	)
}

func (obj View) SetLayoutDirection(layoutDirection_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setLayoutDirection",
		layoutDirection_,
	)
}

func (obj View) SetLeft(left_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setLeft",
		left_,
	)
}

func (obj View) SetLongClickable(longClickable_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setLongClickable",
		longClickable_,
	)
}

func (obj View) SetMinimumHeight(minHeight_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setMinimumHeight",
		minHeight_,
	)
}

func (obj View) SetMinimumWidth(minWidth_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setMinimumWidth",
		minWidth_,
	)
}

func (obj View) SetNextFocusDownId(nextFocusDownId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setNextFocusDownId",
		nextFocusDownId_,
	)
}

func (obj View) SetNextFocusForwardId(nextFocusForwardId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setNextFocusForwardId",
		nextFocusForwardId_,
	)
}

func (obj View) SetNextFocusLeftId(nextFocusLeftId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setNextFocusLeftId",
		nextFocusLeftId_,
	)
}

func (obj View) SetNextFocusRightId(nextFocusRightId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setNextFocusRightId",
		nextFocusRightId_,
	)
}

func (obj View) SetNextFocusUpId(nextFocusUpId_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setNextFocusUpId",
		nextFocusUpId_,
	)
}

func (obj View) SetOverScrollMode(overScrollMode_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setOverScrollMode",
		overScrollMode_,
	)
}

func (obj View) SetPadding(left_ int, top_ int, right_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setPadding",
		left_, top_, right_, bottom_,
	)
}

func (obj View) SetPaddingRelative(start_ int, top_ int, end_ int, bottom_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setPaddingRelative",
		start_, top_, end_, bottom_,
	)
}

func (obj View) SetPivotX(pivotX_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setPivotX",
		android.Float(pivotX_),
	)
}

func (obj View) SetPivotY(pivotY_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setPivotY",
		android.Float(pivotY_),
	)
}

func (obj View) SetPressed(pressed_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setPressed",
		pressed_,
	)
}

func (obj View) SetRight(right_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setRight",
		right_,
	)
}

func (obj View) SetRotation(rotation_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setRotation",
		android.Float(rotation_),
	)
}

func (obj View) SetRotationX(rotationX_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setRotationX",
		android.Float(rotationX_),
	)
}

func (obj View) SetRotationY(rotationY_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setRotationY",
		android.Float(rotationY_),
	)
}

func (obj View) SetSaveEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setSaveEnabled",
		enabled_,
	)
}

func (obj View) SetSaveFromParentEnabled(enabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setSaveFromParentEnabled",
		enabled_,
	)
}

func (obj View) SetScaleX(scaleX_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScaleX",
		android.Float(scaleX_),
	)
}

func (obj View) SetScaleY(scaleY_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScaleY",
		android.Float(scaleY_),
	)
}

func (obj View) SetScrollBarDefaultDelayBeforeFade(scrollBarDefaultDelayBeforeFade_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollBarDefaultDelayBeforeFade",
		scrollBarDefaultDelayBeforeFade_,
	)
}

func (obj View) SetScrollBarFadeDuration(scrollBarFadeDuration_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollBarFadeDuration",
		scrollBarFadeDuration_,
	)
}

func (obj View) SetScrollBarSize(scrollBarSize_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollBarSize",
		scrollBarSize_,
	)
}

func (obj View) SetScrollBarStyle(style_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollBarStyle",
		style_,
	)
}

func (obj View) SetScrollContainer(isScrollContainer_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollContainer",
		isScrollContainer_,
	)
}

func (obj View) SetScrollX(value_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollX",
		value_,
	)
}

func (obj View) SetScrollY(value_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollY",
		value_,
	)
}

func (obj View) SetScrollbarFadingEnabled(fadeScrollbars_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setScrollbarFadingEnabled",
		fadeScrollbars_,
	)
}

func (obj View) SetSelected(selected_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setSelected",
		selected_,
	)
}

func (obj View) SetSoundEffectsEnabled(soundEffectsEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setSoundEffectsEnabled",
		soundEffectsEnabled_,
	)
}

func (obj View) SetSystemUiVisibility(visibility_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setSystemUiVisibility",
		visibility_,
	)
}

func (obj View) SetTextAlignment(textAlignment_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setTextAlignment",
		textAlignment_,
	)
}

func (obj View) SetTextDirection(textDirection_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setTextDirection",
		textDirection_,
	)
}

func (obj View) SetTop(top_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setTop",
		top_,
	)
}

func (obj View) SetTranslationX(translationX_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setTranslationX",
		android.Float(translationX_),
	)
}

func (obj View) SetTranslationY(translationY_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setTranslationY",
		android.Float(translationY_),
	)
}

func (obj View) SetVerticalFadingEdgeEnabled(verticalFadingEdgeEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setVerticalFadingEdgeEnabled",
		verticalFadingEdgeEnabled_,
	)
}

func (obj View) SetVerticalScrollBarEnabled(verticalScrollBarEnabled_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setVerticalScrollBarEnabled",
		verticalScrollBarEnabled_,
	)
}

func (obj View) SetVerticalScrollbarPosition(position_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setVerticalScrollbarPosition",
		position_,
	)
}

func (obj View) SetVisibility(visibility_ int) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setVisibility",
		visibility_,
	)
}

func (obj View) SetWillNotCacheDrawing(willNotCacheDrawing_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setWillNotCacheDrawing",
		willNotCacheDrawing_,
	)
}

func (obj View) SetWillNotDraw(willNotDraw_ bool) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setWillNotDraw",
		willNotDraw_,
	)
}

func (obj View) SetX(x_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setX",
		android.Float(x_),
	)
}

func (obj View) SetY(y_ float64) {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"setY",
		android.Float(y_),
	)
}

func (obj View) ShowContextMenu() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"showContextMenu",
	)
}

func (obj View) ToString() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"toString",
	)
}

func (obj View) WillNotCacheDrawing() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"willNotCacheDrawing",
	)
}

func (obj View) WillNotDraw() {
	android.CallViewMethod(
		obj.GetId(),
		"android.view.View",
		"willNotDraw",
	)
}

